# **Numpy Basics: Arrays & Operations**
*   Introductions to Numpy Arrays
*   Vectors, Matrices, n-Dimensional Arrays
*   Numpy operations
*   How to use the Numpy documentation site




In [ ]:
import numpy as np

# **Numpy Arrays**
Numpy provides a simple way to create and work with matrices, in the form ndarrays (n-dimensional arrays). We can use ndarrays to represent vectors, matrices, or even tensors (higher dimensional matrices). In order to implement a Neural Network, we will learn the basics of ndarrays to perform convenient matrix operations. We'll start by creating a simple array.

In [ ]:
A = np.array([1, 2, 3, 4])

print(A)

[1 2 3 4]


We can think of ndarrays similarly to the way we think of matrices or vectors.

In [ ]:
# We can find the dimensions of A like so:
dim_A = A.shape

print("Dimensions of A: " + str(dim_A))

Dimensions of A: (4,)


As it turns out, A is neither 1 x 4 or 4 x 1. Instead, it is a one-dimensional array, or flattened array, of dimenson 4. Whenever we want to represent vectors in Numpy, we will use one-dimensional arrays. For operations like matrix multiplication, a one-dimensional array can fulfill the role of either a 4 x 1 or 1 x 4 matrix, so they are quite versatile.

You can index into one-dimensional arrays to grab individual indices or slices. You can also modify entries of arrays:

In [ ]:
x = A[0]
print(x)

a_slice = A[1:3]
print(a_slice)

print("Before modifying: {}".format(A))
A[2] = 7
print("After modifying: {}".format(A))

1
[2 3]
Before modifying: [1 2 3 4]
After modifying: [1 2 7 4]


Let's make another array.

In [ ]:
B = np.array([ [1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],
               [13, 14, 15, 16] ])

print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
'''
TODO: print the dimensions of B below
'''
print(B.shape)

(4, 4)


B is a two-dimensional array. These are useful for representing matrices, and they behave similarly to matrices in consideration to most operations.

We can also index into two-dimensional arrays. However, we have more options, as there are two dimensions of indices to index into as opposed to one. Look at some of the following examples:

In [ ]:
print("B:\n" + str(B))
y = B[0, 2]
print("\nA single entry (row 0, col 2) in B: {}".format(y))

B:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

A single entry (row 0, col 2) in B: 3


In [ ]:
print("B:\n" + str(B))
column1 = B[:, 0]
print("\nThe first column in B: {}".format(column1))

B:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

The first column in B: [ 1  5  9 13]


In [ ]:
print("B:\n" + str(B))
row1 = B[0, :]
row2 = B[1]
# we can opt to leave out the second index, numpy will fetch everything in the 2nd dimension
print("\nThe first row in B: {}".format(row1))
print("The second row in B: {}".format(row2))

B:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

The first row in B: [1 2 3 4]
The second row in B: [5 6 7 8]


In [ ]:
crop = B[0:2, 1:3]
print("A crop from B:\n{}".format(crop))

A crop from B:
[[2 3]
 [6 7]]


In [ ]:
# TODO: print one slice containing the last three entries of the third column of B

# indexing crops or submatrices will yield a two-dimensional array
crop = B[1:, 2:3]
print(crop)
print()
# indexing rows or columns will yield one-dimensional arrays
print(B[1:, 2])
# indexing individual entries will yield scalars

[[ 7]
 [11]
 [15]]

[ 7 11 15]


We see that scalar entries make up one-dimensional arrays, which can then be used to make up two-dimensional arrays. It is also true that two-dimensional arrays can be used to make up three-dimensional arrays. 

In general, n-dimensional arrays can be thought of as a collection of (n - 1)-dimensional arrays.

We can represent matrix multiplication and matrix-vector multiplication with np.dot().

In [ ]:
right_product = np.dot(A, B)
print(right_product)
print()

left_product = np.dot(B, A)
print(left_product)

[126 140 154 168]

[ 42  98 154 210]


Similar to matrix multiplication, the order in which you enter arguments into np.dot() is very important.

In [ ]:
'''
TODO: Print out the matrix product between 
the upper-leftmost 3 x 3 crop of B and the lower-rightmost 3 x 3 crop of B. 
Then, replace the upper-rightmost 3 x 3 section of B with that product, and print B.
'''
# Method 1
print("Method 1:\n")
B = np.array([ [1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],
               [13, 14, 15, 16] ])
product = np.dot(B[0:3, 0:3], B[1:, 1:])
print(product)
print()

B[0:3, 1:] = product
print(B)
print()

#Method 2
print("Method 2:\n")
B = np.array([ [1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],
               [13, 14, 15, 16] ])
product = np.dot(B[0:3, 0:3], B[1:4, 1:4])
print(product)
print()

B[0:3, 1:4] = product
print(B)

Method 1:

[[ 68  74  80]
 [188 206 224]
 [308 338 368]]

[[  1  68  74  80]
 [  5 188 206 224]
 [  9 308 338 368]
 [ 13  14  15  16]]

Method 2:

[[ 68  74  80]
 [188 206 224]
 [308 338 368]]

[[  1  68  74  80]
 [  5 188 206 224]
 [  9 308 338 368]
 [ 13  14  15  16]]


There are many ways to instantiate ndarrays in numpy. Here are two common ways:

In [ ]:
zero_array = np.zeros((2, 2))
print(zero_array)
print()

random_array = np.random.rand(4, 3)  # fills array with values between 0 and 1
print(random_array)

[[0. 0.]
 [0. 0.]]

[[0.26903305 0.50120951 0.20380465]
 [0.56851198 0.2260302  0.38313511]
 [0.10283139 0.74084305 0.33409616]
 [0.01124245 0.739842   0.22890275]]


Both of these ways of instantiating arrays involve entering the desired dimensions into their respective functions. However, np.zeros() requires the dimensions to be contained inside parentheses, while np.random.rand() wants the dimensions to be entered as separate arguments. These small details are always difficult to remember, so you may often have to refer to the [numpy documentation](https://numpy.org/doc/stable/reference/index.html).

In [ ]:
'''
TODO: Constuct a random 5 x 4 array. Matrix multiply (use np.dot()) this with B and then print the result.
      Remember, order matters!
'''
C = np.random.rand(5, 4)
new_product = np.dot(C, B)
print(new_product)

[[  8.59493971 192.26861233 210.66054608 229.05247983]
 [ 10.77365625 190.1491451  208.24786846 226.34659183]
 [ 17.40369738 252.98372168 276.82761347 300.67150526]
 [  9.22707811 216.11804616 236.41251097 256.70697577]
 [ 13.66340244 111.56985042 121.70524236 131.8406343 ]]
